# ==============================================================================
# AMCL定位配置（修正TF广播冲突）
# ==============================================================================
amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    max_particles: 500              # 降低粒子数量（原1000）
    min_particles: 200              # 降低粒子数量（原300）
    laser_likelihood_max_dist: 2.0  # 缩短有效距离（原3.0）
    laser_model_type: "likelihood_field"
    update_min_a: 0.3               # 增大角度阈值（原0.2）
    update_min_d: 0.3               # 增大距离阈值（原0.25）
    scan_topic: scan
    imu_gain: 0.0
    imu_options: 0
    tf_broadcast: false
    publish_frame_provider: "amcl"
    publish_particlecloud: false
    scan_queue_size: 50             # 新增：AMCL输入队列扩容

# ==============================================================================
# 行为树导航器配置（基于行为树的任务执行框架）
# ==============================================================================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: "base_footprint"
    odom_topic: /odom
    bt_loop_duration: 20            # 延长行为树周期（原10）
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_recovery_node_bt_node

# ==============================================================================
# 控制器服务器配置（DWB动态窗口本地规划器）
# ==============================================================================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0      # 降低控制频率（原20.0）
    controller_plugins: ["FollowPath"]
    
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: 0.0
      max_vel_x: 0.25               # 降低最大线速度（原0.3）
      max_vel_theta: 0.6            # 降低最大角速度（原0.8）
      acc_lim_x: 0.8                # 降低加速度（原1.0）
      acc_lim_theta: 1.5            # 降低角加速度（原2.0）
      vx_samples: 15                # 减少采样数（原20）
      vtheta_samples: 15             # 减少采样数（原20）
      sim_time: 1.2                 # 缩短预测时间（原1.5）
      linear_granularity: 0.05
      angular_granularity: 0.03
      transform_tolerance: 0.1
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.08
      trans_stopped_velocity: 0.005
      short_circuit_trajectory_evaluation: true
      stateful: true
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "ObstacleCost"]
      BaseObstacle.scale: 0.1
      ObstacleCost.scale: 40.0       # 降低障碍物代价（原50.0）
      RotateToGoal.scale: 28.0       # 降低旋转代价（原32.0）
      PathAlign.scale: 28.0          # 降低路径对齐代价（原32.0）
      GoalAlign.scale: 20.0          # 降低目标对齐代价（原24.0）

# ==============================================================================
# 局部代价地图配置（实时更新的障碍物地图）
# ==============================================================================
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0         # 降低更新频率（原10.0）
      publish_frequency: 3.0         # 降低发布频率（原5.0）
      global_frame: odom
      robot_base_frame: "base_footprint"
      use_sim_time: true
      rolling_window: true
      width: 4                       # 减小尺寸（原5）
      height: 4                      # 减小尺寸（原5）
      resolution: 0.075              # 降低分辨率（原0.05）
      robot_radius: 0.1
      
      plugins: ["voxel_layer", "inflation_layer"]
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.3
      
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: false
        origin_z: 0.12
        z_resolution: 0.15           # 降低Z轴分辨率（原0.1）
        z_voxels: 15                 # 减少Z轴体素（原20）
        max_obstacle_height: 1.0     # 降低障碍物高度（原1.62）
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.5   # 降低（原2.0）
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 4.0    # 缩短（原5.0）
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5    # 缩短（原3.0）
          obstacle_min_range: 0.1
        queue_size: 50               # 新增：体素层输入队列

# ==============================================================================
# 全局代价地图配置（静态地图与障碍物）
# ==============================================================================
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 0.5          # 降低更新频率（原1.0）
      publish_frequency: 0.5         # 降低发布频率（原1.0）
      global_frame: map
      robot_base_frame: "base_footprint"
      use_sim_time: true
      robot_radius: 0.1
      resolution: 0.075              # 降低分辨率（原0.05）
      track_unknown_space: true
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.5   # 降低（原2.0）
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 4.0    # 缩短（原5.0）
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5    # 缩短（原3.0）
          obstacle_min_range: 0.1
        queue_size: 50               # 新增：障碍物层输入队列
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.3
      always_send_full_costmap: true

# ==============================================================================
# 地图服务器配置（加载和管理地图）
# ==============================================================================
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""

# ==============================================================================
# 路径规划器配置（全局路径规划）
# ==============================================================================
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.3
      allow_unknown: false

# ==============================================================================
# 行为服务器配置（导航恢复行为集合）- 修正版
# ==============================================================================
behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 5.0             # 降低行为执行频率（原10.0）
    
    # 确保声明的插件都有对应配置
    behavior_plugins: ["spin", "backup", "drive_on_heading", "recovery_turn"]
    
    spin:
      plugin: "nav2_behaviors/Spin"
      max_rotational_vel: 0.4        # 降低旋转速度（原0.5）
      min_rotational_vel: 0.15       # 降低（原0.2）
      acceleration_limits:
        rotational: 0.8              # 降低（原1.0）
    
    backup:
      plugin: "nav2_behaviors/BackUp"
      max_linear_vel: -0.12          # 降低速度（原-0.15）
      min_linear_vel: -0.04          # 降低（原-0.05）
      backup_distance: 0.3
    
    # 新增缺失的drive_on_heading配置
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      max_linear_vel: 0.15           # 合理默认值
      min_linear_vel: 0.05
      linear_acceleration: 0.5
      max_drive_distance: 1.0        # 最大驱动距离
    
    recovery_turn:
      plugin: "nav2_behaviors/RecoveryTurn"
      max_rotational_vel: 0.4        # 降低（原0.5）
      min_rotational_vel: 0.15       # 降低（原0.2）
      turn_angle: 0.8                # 减小旋转角度（原1.0）
    
    global_frame: map
    robot_base_frame: "base_footprint"
    transform_tolerance: 0.1
    use_sim_time: true
    simulate_ahead_time: 1.5         # 缩短模拟时间（原2.0）

# ==============================================================================
# 机器人状态发布器配置（发布机器人模型状态）
# ==============================================================================
robot_state_publisher:
  ros__parameters:
    use_sim_time: true
    publish_frequency: 10.0          # 降低发布频率（默认50Hz）
    ignore_timestamp: true            # 新增：避免时间同步问题

# ==============================================================================
# 安全控制器配置（紧急避障与速度限制）- 修正缩进
# ==============================================================================
safety_controller:
  ros__parameters:                    # 修正缩进错误
    use_sim_time: true
    scan_topic: /scan
    cmd_vel_in_topic: /cmd_vel_nav
    cmd_vel_out_topic: /cmd_vel
    
    max_linear_vel_x: 0.25           # 降低（原0.3）
    min_linear_vel_x: -0.15          # 降低（原-0.2）
    max_angular_vel_z: 0.6           # 降低（原0.8）
    min_angular_vel_z: -0.6          # 降低（原-0.8）
    
    emergency_stop_distance: 0.3
    slow_down_distance: 0.5
    front_angle: 0.785                # 减小检测角度（原1.047→60度→45度）
    min_speed_threshold: 0.03
    queue_size: 50                    # 新增：安全控制器输入队列

# ==============================================================================
# Robot Localization配置（IMU与里程计融合定位）
# ==============================================================================
robot_localization:
  ros__parameters:
    ekf_filter_node:
      ros__parameters:
        frequency: 20.0              # 降低频率（原30.0）
        sensor_timeout: 0.15         # 增加超时（原0.1）
        two_d_mode: true
        publish_tf: false
        tf_broadcast_frame_id: "odom"
        tf_listener_timeout: 0.2     # 增加超时（原0.1）
        
        base_link_frame: "base_footprint"
        odom_frame: odom
        world_frame: map
        
        odom0: /odom
        odom0_config: [true, true, false,
                      false, false, true,
                      true, true, false,
                      false, false, true,
                      false, false, false]
        odom0_queue_size: 20         # 增大队列（原10）
        
        imu0: /imu/data
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      false, false, false]
        imu0_queue_size: 20          # 增大队列（原10）
        imu0_differential: false
        imu0_relative: true
        imu0_remove_gravitational_acceleration: true
        
        process_noise_covariance: [
          0.05, 0, 0, 0, 0, 0,     # 增大噪声容忍度
          0, 0.05, 0, 0, 0, 0,
          0, 0, 0.05, 0, 0, 0,
          0, 0, 0, 0.05, 0, 0,
          0, 0, 0, 0, 0.05, 0,
          0, 0, 0, 0, 0, 0.05
        ]
    
    navsat_transform_node:
      ros__parameters:
        frequency: 0.5               # 降低频率（原1.0）
        two_d_mode: true
        publish_filtered_gps: true
        magnetic_declination_radians: 0.0
        yaw_offset: 0.0
        zero_altitude: true
        wait_for_datum: false
        broadcast_utm_transform: false

# ==============================================================================
# RViz2专用优化配置（防止队列溢出和崩溃）
# ==============================================================================
rviz:
  ros__parameters:
    use_sim_time: true
    visualization:
      queue_size: 200                # 大幅增加RViz2队列容量
      max_update_rate: 10.0          # 限制最大刷新率（Hz）
    displays:
      - name: "LaserScan"
        class: "rviz_default_plugins/LaserScan"
        topic: "/scan"
        queue_size: 100              # 激光显示专用队列
        style: "Points"              # 使用点云模式（比环状节省资源）
        size: 0.03                   # 减小点云尺寸
        alpha: 0.6                   # 增加透明度
        filter_epsilon: 0.05         # 点云滤波减少显示点数
      - name: "Map"
        class: "rviz_default_plugins/Map"
        topic: "/map"
        queue_size: 30
      - name: "Path"
        class: "rviz_default_plugins/Path"
        topic: "/plan"
        queue_size: 30
        line_width: 0.02             # 减小路径线宽